name: "Synopsys Intelligent Security Scan"

on:
  push:
   branches: [ test ]
#   pull_request:
#     branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    
    - name: Synopsys Intelligent Security Scan
      id: prescription
      uses: akshayme-synp/intelligent-security-scan@try-branch
      env:
        persona: developer
        release_type: major
        manifest_type: json
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowVersion: 2021.12.2
        additionalWorkflowArgs: --slack.channel.id=${{secrets.SLACK_CHANNEL_ID}} --slack.token=${{secrets.SLACK_TOKEN}} --persona=$persona --release.type=$release_type --manifest_type=$manifest_type --github.token=${{secrets.SCM_ACCESS_TOKEN}} --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}}
        stage: "IO"

    # Please note that the ID in previous step was set to prescription
    # in order for this logic to work also make sure that POLARIS_ACCESS_TOKEN
    # is defined in settings
    - name: Incremental Static Analysis with Polaris
      run: |
          git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} > polaris-files-to-scan.txt
          echo "Files Changed -->"
          cat polaris-files-to-scan.txt
          export POLARIS_SERVER_URL=${{ secrets.POLARIS_SERVER_URL}}
          export POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN}}
          export POLARIS_FF_ENABLE_COVERITY_INCREMENTAL=true
          wget -q ${{ secrets.POLARIS_SERVER_URL}}/api/tools/polaris_cli-linux64.zip
          unzip -j polaris_cli-linux64.zip -d /tmp
          /tmp/polaris analyze -w --incremental polaris-files-to-scan.txt
    
#     # Please note that the ID in previous step was set to prescription
#     # in order for this logic to work also make sure that POLARIS_ACCESS_TOKEN
#     # is defined in settings
#     - name: Static Analysis with Polaris
#       if: ${{steps.prescription.outputs.sastScan == 'true' }}
#       run: |
#           export POLARIS_SERVER_URL=${{ secrets.POLARIS_SERVER_URL}}
#           export POLARIS_ACCESS_TOKEN=${{ secrets.POLARIS_ACCESS_TOKEN}}
#           wget -q ${{ secrets.POLARIS_SERVER_URL}}/api/tools/polaris_cli-linux64.zip
#           unzip -j polaris_cli-linux64.zip -d /tmp
#           /tmp/polaris analyze -w
    
#     # Please note that the ID in previous step was set to prescription
#     # in order for this logic to work
#     - name: Software Composition Analysis with Black Duck
#       if: ${{steps.prescription.outputs.scaScan == 'true' }}
#       uses: blackducksoftware/github-action@v2
#       with:
#          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_TOKEN}}" --detect.tools="SIGNATURE_SCAN,DETECTOR"'
    
    - name: Synopsys Intelligent Security Scan
      if: ${{ steps.prescription.outputs.sastScan == 'true' || steps.prescription.outputs.scaScan == 'true' }}
      uses: akshayme-synp/intelligent-security-scan@try-branch
      env:
        persona: developer
        release_type: major
        manifest_type: json
      with:
        ioServerUrl: ${{secrets.IO_SERVER_URL}}
        ioServerToken: ${{secrets.IO_SERVER_TOKEN}}
        workflowServerUrl: ${{secrets.WORKFLOW_SERVER_URL}}
        workflowVersion: 2021.12.2
        additionalWorkflowArgs: --slack.channel.id=${{secrets.SLACK_CHANNEL_ID}} --slack.token=${{secrets.SLACK_TOKEN}} --persona=$persona --release.type=$release_type --manifest_type=$manifest_type --github.token=${{secrets.SCM_ACCESS_TOKEN}} --polaris.url=${{secrets.POLARIS_SERVER_URL}} --polaris.token=${{secrets.POLARIS_ACCESS_TOKEN}} --IS_SAST_ENABLED=${{steps.prescription.outputs.sastScan}} --IS_SCA_ENABLED=${{steps.prescription.outputs.scaScan}} --IS_DAST_ENABLED=false
        stage: "WORKFLOW"
        
    - name: Upload Artifact to GitHub
      if: ${{steps.prescription.outputs.sastScan == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: "scan results"
        path: |
            workflowengine-results.sarif
            /home/runner/work/github-io-sample/github-io-sample/.synopsys/polaris/data/coverity/2021.12.1/idir/incremental-results/
    
#     - name: Upload SARIF file
#       if: ${{steps.prescription.outputs.sastScan == 'true' }}
#       uses: github/codeql-action/upload-sarif@v1
#       with:
#         # Path to SARIF file relative to the root of the repository
#         sarif_file: workflowengine-results.sarif
