name: "Try powershell"

on:
  push:
   branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
        
    - name: Run powershell
      shell: pwsh
      run: |
        .\prescription.ps1
